/**
 * @license
 * PXT Blockly
 *
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * https://github.com/Microsoft/pxt-blockly
 *
 * See LICENSE file for details.
 */
"use strict";goog.provide("Blockly.FieldString"),goog.require("Blockly.FieldTextInput"),goog.require("Blockly.utils.object"),goog.require("Blockly.utils.userAgent"),Blockly.FieldString=function(t,e,i){Blockly.FieldString.superClass_.constructor.call(this,t,e),this.setRestrictor(i),this.addArgType("text")},Blockly.utils.object.inherits(Blockly.FieldString,Blockly.FieldTextInput),Blockly.FieldString.fromJson=function(t){var e=Blockly.utils.replaceMessageReferences(t.text),i=new Blockly.FieldString(e,t.class);return"boolean"==typeof t.spellcheck&&i.setSpellcheck(t.spellcheck),i},Blockly.FieldString.quotePadding=0,Blockly.FieldString.prototype.initView=function(){this.quoteSize_=16,this.quoteWidth_=8,this.quoteLeftX_=0,this.quoteRightX_=0,this.quoteY_=10,this.quoteLeft_&&this.quoteLeft_.parentNode.removeChild(this.quoteLeft_),this.quoteLeft_=Blockly.utils.dom.createSvgElement("text",{"font-size":this.quoteSize_+"px",class:"field-text-quote"},this.fieldGroup_),Blockly.FieldString.superClass_.initView.call(this),this.quoteRight_&&this.quoteRight_.parentNode.removeChild(this.quoteRight_),this.quoteRight_=Blockly.utils.dom.createSvgElement("text",{"font-size":this.quoteSize_+"px",class:"field-text-quote"},this.fieldGroup_),this.quoteLeft_.appendChild(document.createTextNode('"')),this.quoteRight_.appendChild(document.createTextNode('"')),this.mouseOverWrapper_=Blockly.bindEvent_(this.getClickTarget_(),"mouseover",this,this.onMouseOver_),this.mouseOutWrapper_=Blockly.bindEvent_(this.getClickTarget_(),"mouseout",this,this.onMouseOut_)},Blockly.FieldString.prototype.updateSize_=function(){Blockly.FieldString.superClass_.updateSize_.call(this);var t=this.value_?this.size_.width:1,e=this.positionLeft(t+3);this.textElement_.setAttribute("x",e),e+=this.positionRight(e+t+3),this.size_.width=t+e},Blockly.FieldString.prototype.positionLeft=function(t){if(!this.quoteLeft_)return 0;var e=0;return this.sourceBlock_.RTL?(this.quoteLeftX_=t+this.quoteWidth_+2*Blockly.FieldString.quotePadding,e=this.quoteWidth_+Blockly.FieldString.quotePadding):(this.quoteLeftX_=0,e=this.quoteWidth_+Blockly.FieldString.quotePadding),this.quoteLeft_.setAttribute("transform","translate("+this.quoteLeftX_+","+this.quoteY_+")"),e},Blockly.FieldString.prototype.positionRight=function(t){if(!this.quoteRight_)return 0;var e=0;return this.sourceBlock_.RTL?(this.quoteRightX_=Blockly.FieldString.quotePadding,e=this.quoteWidth_+Blockly.FieldString.quotePadding):(this.quoteRightX_=t+Blockly.FieldString.quotePadding,e=this.quoteWidth_+Blockly.FieldString.quotePadding),this.quoteRight_.setAttribute("transform","translate("+this.quoteRightX_+","+this.quoteY_+")"),e},Blockly.fieldRegistry.register("field_string",Blockly.FieldString);